### ISSUE TITLE
question about dataset 

### ISSUE THREAD

**Issue by Gowott** [SparkJiao/LARCH#2]
Hi,there,
it seems that **train_2.tar.gz** is not the correct compressed file,
since I try several times but still can not decompress it successfully and it is not compressed file when I try commend 'file' to check it is format.
![image](https://user-images.githubusercontent.com/79396054/168746567-f1d8b10a-7611-4537-95d8-ebbae5df8a13.png)
![image](https://user-images.githubusercontent.com/79396054/168746603-35055590-ae01-42f4-aa43-fd7dafbecf4b.png)
And also, although train_1 can be decompressed, something wrong also goes with it as the image followed,
![image](https://user-images.githubusercontent.com/79396054/168747229-4b8be163-e85b-4694-ac37-2ef659e54c32.png)
Could you please check whether they are okay and upload these 2 files again?

**Comment by SparkJiao** [comment]
Hi, please use following command under linux to combine the splitted files first
```
cat train_*.tar.gz > train.tar.gz
```
And then you can decompress it normally.

If you have more questions, please reopen this issue.
