### ISSUE TITLE
为啥image_id和url2img对不上阿？

### ISSUE THREAD

**Issue by Gowott** [SparkJiao/LARCH#3]
![image](https://user-images.githubusercontent.com/79396054/177992236-487ce046-e1eb-442d-96ec-7668c0b234c7.png)
![image](https://user-images.githubusercontent.com/79396054/177992277-8457ac2c-60b0-4888-be89-b0eb125393da.png)
image_id有59W+，但是url2img只有40W，
请问你是怎么使用的呢？

**Comment by Gowott** [comment]
还有个问题是，请问有上传好的images文件吗，你们组另一个工作给到的images是48W+左右的图片

**Comment by SparkJiao** [comment]
hi，您好，image的数量多于url的数量很正常，因为有些图片无法下载，实际上只需要确保原始数据集中的正例图片都已经被保存了即可，负例图片是随机采样的，并且在于baseline比较时每个模型使用的都是相同的正例和负例，因此也不需要担心公平性的问题。

关于图片，以及其他的知识图谱等信息，直接使用原始MMD数据集的即可。
